# ✅ Remove version — it's deprecated
# version: "3.9"  <-- remove this line

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - note-app
    restart: always  
    depends_on:
      - django

  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - note-app  
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
  
  django:
    build: 
      context: .
    container_name: django_cont
    command: >
      sh -c "python manage.py migrate --no-input && gunicorn notesapp.wsgi:application --bind 0.0.0.0:8000"
    env_file: 
      - .env
    ports:
      - "8000:8000"
    networks:
      - note-app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/admin/ || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes: 
  mysql_data:

networks: 
  note-app:
